export const shopArray = [
  {
    id: 1,
    name: "Nolan N100",
    description: "This is Nolan N100 Pro",
    capacity: 512,
    type: "helmet",
    price: 2000,
    image: "/images/demon-150-gr.jpeg",
    category: "bikes",
    all: "all",
  },
  {
    id: 2,
    name: "Nolan N33",
    description: "This is Nolan N33 Pro",
    capacity: 256,
    type: "bike",
    price: 1850,
    image: "/images/n-100.jpeg",
    category: "helmets",
    all: "all",
  },
  {
    id: 3,
    name: "Nolan N21",
    description: "This is Nolan N21 Pro",
    capacity: 128,
    type: "helmet",
    price: 1600,
    image: "/images/demon-150-gr.jpeg",
    category: "bikes",
    all: "all",
  },
  {
    id: 4,
    name: "Nolan N70",
    description: "This is Nolan N33 Xs",
    capacity: 256,
    type: "bike",
    price: 1400,
    image: "/images/n-100.jpeg",
    category: "helmets",
    all: "all",
  },
  {
    id: 5,
    name: "Grex",
    description: "This is Nolan N33 Xr",
    capacity: 256,
    type: "helmet",
    price: 1200,
    image: "/images/n-100.jpeg",
    category: "helmets",
    all: "all",
  },
  {
    id: 6,
    name: "X-Lite 1000",
    description: "This is Nolan N33 8",
    capacity: 256,
    type: "bike",
    price: 1000,
    image: "/images/n-100.jpeg",
    category: "helmets",
    all: "all",
  },
  {
    id: 7,
    name: "X-Lite 500",
    description: "This is Nolan N33 8",
    capacity: 256,
    type: "helmet",
    price: 1000,
    image: "/images/n-100.jpeg",
    category: "helmets",
    all: "all",
  },
  {
    id: 8,
    name: "X-Lite 200",
    description: "This is Nolan N33e 8",
    capacity: 256,
    type: "bike",
    price: 1000,
    image: "/images/n-100.jpeg",
    category: "helmets",
    all: "all",
  },
  {
    id: 9,
    name: "X-Lite 300",
    description: "This is Nolan N33 8",
    capacity: 256,
    type: "helmet",
    price: 1000,
    image: "/images/n-100.jpeg",
    category: "helmets",
    all: "all",
  },
  {
    id: 10,
    name: "X-Lite 700",
    description: "This is iPhone 8",
    capacity: 256,
    type: "phone",
    price: 1000,
    image: "/images/n-100.jpeg",
    category: "helmets",
    all: "all",
  },
];

// export const getShopObject = (array) => {
//   return array.reduce(
//     (obj, product) => ({
//       ...obj,
//       [product.id]: product,
//     }),
//     {}
//   );
// };
